@endpoint = http://localhost:8000/user 


### 회원가입
POST {{endpoint}}/signup HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email": "seungsu123@gmail.com",
    "password": "12345"
}


### 로그인
POST {{endpoint}}/signin HTTP/1.1
Content-Type: multipart/form-data;boundary="WebKitFormBoundaryAB"
Accept: application/json

--WebKitFormBoundaryAB
Content-Disposition: form-data; name="username"

seungsu123@gmail.com
--WebKitFormBoundaryAB
Content-Disposition: form-data; name="password"

12345
--WebKitFormBoundaryAB--


### JWT 테스트
GET {{endpoint}}/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNldW5nc3VAZ21haWwuY29tIiwiZXhwaXJlcyI6MTcwODI2NjA5OC4xMDExNzU4fQ.aS7jdH7Ma2oDvzpseez76VUUW51tXMrfYVorTdXTV08
Accept: application/json


### 토큰 재발급
POST {{endpoint}}/refresh HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Accept: application/json

email=seungsu123@gmail.com

